config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :games, only: %i[show], shallow: true do
    resources :new_players, only: %i[create new]

    resources :players, only: %i[edit update], shallow: true do
      resources :turns, only: %i[create new]
    end

    resources :rounds, only: %i[show], shallow: true do
      resources :completed_rounds, only: %i[create]
      resources :participants, only: %i[], shallow: true do
        resources :votes, only: %i[create update]
      end
    end
  end

  resources :new_games, only: %i[create new]

  root "new_games#new"

  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
end

app/controllers/new_players_controller.rb
# frozen_string_literal: true

class NewPlayersController < ApplicationController
  # GET /games/:game_id/new_players/new
  def new
    @new_player = NewPlayerForm.new(game:, user: @user)
  end

  # POST /games/:game_id/new_players
  def create
    @new_player = NewPlayerForm.new(game:, user: @user, **new_player_params)

    if @new_player.save
      game.active_players.each do |player|
        next if player == @new_player.player

        PlayerChannel.broadcast_append_later_to(
          player,
          target: "vote_candidate_id",
          partial: "votes/candidate",
          locals: { candidate: @new_player.participant, selected: false }
        )
        PlayerChannel.broadcast_append_later_to(
          player,
          target: "players",
          partial: "players/player",
          locals: {
            player: @new_player.player, judge: game.current_judge, me: player
          }
        )
      end
      redirect_to game
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # @return [Game]
  def game
    @game ||= Game.find(params[:game_id])
  end

  # @return [ActionController::Parameters]
  def new_player_params
    params.require(:new_player_form).permit(player_attributes: %i[name])
  end
end

app/views/new_players/new.html.erb
<h3 class="mt-2 mb-4">Create your player to join this game:</h3>

<%= simple_form_for(@new_player, url: game_new_players_path(@new_player.game) ) do |form| %>
  <%= form.error_notification %>
  <%- form.object.errors.to_hash(true).except(:player).each_value do |error_msgs| -%>
    <%= form.error_notification message: error_msgs.to_sentence %>
  <%- end -%>

  <%= form.simple_fields_for :player do |player_form| %>
    <%- player_form.object.errors.to_hash(true).except(:name).each_value do |error_msgs| -%>
      <%= player_form.error_notification message: error_msgs.to_sentence %>
    <%- end -%>

    <%= player_form.input :name, label: "Player name", input_html: { maxlength: 20 } %>
  <% end %>

  <div class="d-grid gap-2">
    <%= form.button :submit, "Create New Player", class: "btn-primary btn-lg" %>
  </div>
<% end %>