config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :games, only: %i[show], shallow: true do
    resources :new_players, only: %i[create new]

    resources :players, only: %i[edit update], shallow: true do
      resources :turns, only: %i[create new]
    end

    resources :rounds, only: %i[show], shallow: true do
      resources :completed_rounds, only: %i[create]
      resources :participants, only: %i[], shallow: true do
        resources :votes, only: %i[create update]
      end
    end
  end

  resources :new_games, only: %i[create new]

  root "new_games#new"

  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
end

app/controllers/turns_controller.rb
# frozen_string_literal: true

class TurnsController < ApplicationController
  # GET /players/:player_id/turns/new
  def new
    @turn = TurnForm.new(judge: current_player)
  end

  # POST /players/:player_id/turns
  def create
    @turn = TurnForm.new(judge: current_player, **turn_params)

    if @turn.save
      game = Game.find(@turn.game.id) # work from latest data

      # Show the Next Turn link to all other players
      game.active_players.each do |player|
        PlayerChannel.broadcast_update_later_to(
          player,
          target: "players",
          collection: game.active_players,
          partial: "players/player",
          locals: { judge: game.current_judge, me: player }
        )
        next if player == current_player

        PlayerChannel.broadcast_update_to(
          player,
          target: "new_turn",
          partial: "games/current_round_link",
          locals: { game: }
        )
      end

      redirect_to game
    else
      render :create, status: :unprocessable_entity
    end
  end

  private

  # @return [Player]
  def current_player
    @current_player ||= Player.where(user: @user).find(params[:player_id])
  end

  # @return [ActionController::Parameters]
  def turn_params
    params.require(:turn_form)
      .permit(round_attributes: %i[question least_likely hide_voters])
  end
end

app/views/turns/_form.html.erb
<%= simple_form_for turn, url: player_turns_path(turn.judge) do |form| %>
  <%= form.error_notification %>
  <%- form.object.errors.to_hash(true).except(:round).each_value do |error_msgs| -%>
    <%= form.error_notification message: error_msgs.to_sentence %>
  <%- end -%>

  <%= form.simple_fields_for :round do |round_form| %>
    <%- round_form.object.errors.to_hash(true).except(:question).each_value do |error_msgs| -%>
      <%= round_form.error_notification message: error_msgs.to_sentence %>
    <%- end -%>

    <%=
      round_form.input :least_likely,
        legend_tag: false,
        as: :radio_buttons,
        collection: [[false, "Most likely to..."], [true, "Least likely to..."]],
        label_method: :second,
        value_method: :first
    %>
    <%= round_form.input :question, as: :text, label: false, input_html: { maxlength: 160 } %>
    <%= round_form.input :hide_voters, as: :boolean %>
  <%- end -%>

  <div class="d-grid gap-2">
    <%= form.button :submit, "Create Next Turn", class: "btn-primary btn-lg" %>
  </div>
<% end %>

app/views/turns/create.turbo_stream.erb
<%= turbo_stream.update "main" do %>
  <%= render "form", turn: @turn %>
<% end %>

app/views/turns/new.html.erb
<h1>Next Turn</h1>

<%= turbo_frame_tag("main") do %>
  <%= render "form", turn: @turn %>
<% end %>