config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :games, only: %i[show], shallow: true do
    resources :new_players, only: %i[create new]

    resources :players, only: %i[edit update], shallow: true do
      resources :turns, only: %i[create new]
    end

    resources :rounds, only: %i[show], shallow: true do
      resources :completed_rounds, only: %i[create]
      resources :participants, only: %i[], shallow: true do
        resources :votes, only: %i[create update]
      end
    end
  end

  resources :new_games, only: %i[create new]

  root "new_games#new"

  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
end

app/controllers/new_games_controller.rb
# frozen_string_literal: true

class NewGamesController < ApplicationController
  # GET /new_games/new
  def new
    @new_game = NewGameForm.new(user: @user)
  end

  # POST /new_games
  def create
    @new_game = NewGameForm.new(user: @user, **new_game_params)

    if @new_game.save
      redirect_to game_path(@new_game.game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # @return [ActionController::Parameters]
  def new_game_params
    params.require(:new_game_form)
      .permit(
        player_attributes: %i[name],
        round_attributes: %i[question least_likely hide_voters]
      )
  end
end

app/views/new_games/new.html.erb
<h1 class="my-2">Burn Unit</h1>

<%= simple_form_for @new_game, url: new_games_path do |form| %>
  <%= form.error_notification %>
  <%- form.object.errors.to_hash(true).except(:player, :round).each_value do |error_msgs| -%>
    <%= form.error_notification message: error_msgs.to_sentence %>
  <%- end -%>

  <%= form.simple_fields_for :player do |player_form| %>
    <%- player_form.object.errors.to_hash(true).except(:name).each_value do |error_msgs| -%>
      <%= player_form.error_notification message: error_msgs.to_sentence %>
    <%- end -%>

    <%= player_form.input :name, label: "Player name", input_html: { maxlength: 20 } %>
  <% end %>

  <%= form.simple_fields_for :round do |round_form| %>
    <%- round_form.object.errors.to_hash(true).except(:question).each_value do |error_msgs| -%>
      <%= round_form.error_notification message: error_msgs.to_sentence %>
    <%- end -%>

    <%=
      round_form.input :least_likely,
        legend_tag: false,
        as: :radio_buttons,
        collection: [[false, "Most likely to..."], [true, "Least likely to..."]],
        label_method: :second,
        value_method: :first
    %>
    <%= round_form.input :question, as: :text, label: false, input_html: { maxlength: 160 } %>
    <%= round_form.input :hide_voters, as: :boolean %>
  <% end %>

  <div class="d-grid gap-2">
    <%= form.button :submit, "Create New Game", class: "btn-primary btn-lg" %>
  </div>
<% end %>